export const INCREMENT="INCREMENT"
export const DECREMENT="DECREMENT"
export const ADD="ADD"
export const SUBTRACT="SUBTRACT"
export const DIVIDE="DIVIDE"
export const MULTIPLY="MULTIPLY"
export const X="X"